# Generated by Django 5.1.1 on 2024-09-09 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_markagenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markagenda',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.agenda', verbose_name='Agenda'),
        ),
        migrations.AlterField(
            model_name='markagenda',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
